version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - "9229:9229"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=movie_db
    volumes:
      - ../pg_data:/var/lib/postgresql/data
