version: "3.7"
services:

  app:
    build: .
    container_name: node-express-app
    image: node-app:1.0.0
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=holiday_db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
