version: '3.7'
services:
  static_site:
    build: .
    container_name: static_html_site
    image: static_site:1.0.0
    ports:
      - 8000:80
    volumes:
      - ./pages/:/usr/share/nginx/html/
    
    